# Generated by Django 2.0 on 2018-05-13 19:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('accession', 'Accession'), ('agent', 'Agent'), ('collection', 'Collection'), ('component', 'Component'), ('term', 'Term')], max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('aurora', 'Aurora')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerObject',
            fields=[
                ('dataobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transformer.DataObject')),
                ('consumer', models.CharField(choices=[('archivesspace', 'ArchivesSpace'), ('fedora', 'Fedora')], max_length=50)),
                ('source_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_object', to='transformer.SourceObject')),
            ],
            bases=('transformer.dataobject',),
        ),
    ]
