# Generated by Django 2.0.8 on 2018-11-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0002_auto_20181009_0249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfer',
            new_name='Package',
        ),
    ]
