# Generated by Django 2.2.6 on 2020-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0006_package_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='origin',
            field=models.CharField(choices=[('aurora', 'Aurora'), ('legacy_digital', 'Legacy Digital Processing'), ('digitization', 'Digitization')], default='aurora', max_length=20),
        ),
    ]
