# Generated by Django 2.2.10 on 2020-03-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    def asterism_values(apps, schema_editor):
        Package = apps.get_model('transformer', 'Package')
        for package in Package.objects.all():
            package.bag_identifier = package.identifier
            package.type = package.package_type
            package.data = package.transfer_data
            package.save()

    def revert_asterism_values(apps, schema_editor):
        Package = apps.get_model('transformer', 'Package')
        for package in Package.objects.all():
            package.identifier = package.bag_identifier
            package.package_type = package.type
            package.transfer_data = package.data
            package.save()

    dependencies = [
        ('transformer', '0007_auto_20200317_0016'),
    ]

    operations = [
        migrations.RunPython(asterism_values, revert_asterism_values)
    ]
