# Generated by Django 2.2.10 on 2020-03-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0008_auto_20200317_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='package',
            name='transfer_data',
        ),
    ]
