# Generated by Django 2.2.10 on 2020-03-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0009_auto_20200317_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='bag_identifier',
            field=models.CharField(max_length=255),
        ),
    ]
