# Generated by Django 3.2.5 on 2021-07-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0010_auto_20200317_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='accession_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
