# Generated by Django 2.0 on 2018-04-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_1', models.CharField(max_length=4)),
                ('segment_2', models.CharField(blank=True, max_length=3, null=True)),
                ('segment_3', models.CharField(blank=True, max_length=3, null=True)),
                ('segment_4', models.CharField(blank=True, max_length=3, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('in_archivesspace', models.BooleanField()),
            ],
        ),
    ]
